### ISSUE TITLE
Consider migrating to ember-test-waiters?

### ISSUE THREAD

**Issue by rwjblue** [bendemboski/ember-concurrency-test-waiter#12]
The integration from ember-test-waiters with `@ember/test-helpers` significantly aids debugging when things are not settling (it emits stack traces for the locations that kick off async, and the name of the waiter that is not settled, etc).

I'd love your thoughts?

**Comment by bendemboski** [comment]
Yeah, I think it's a great idea. It should be pretty trivial to replace the `taskRunCounter` incrementing and decrementing [here](https://github.com/bendemboski/ember-concurrency-test-waiter/blob/master/addon/with-test-waiter.js#L22-L27) with `waiter.beginAsync` and `waiter.endAsync` calls.

What would be really slick is if we could access the name of the task (or something) from that code so we could name the waiter something helpful. And/or we could allow the caller to pass in a name I guess.

I have been wondering about the future of this in the Octane/decorator world, though. This is maybe a tangent, but maybe relevant -- what would the API look like? One option would be to instrument `ember-concurrency-decorators` to allow

```javascript
@task({ withTestWaiter: true, restartable: true })
*doSomething() {
}
```

But I wonder if a different solution that also doesn't rely on intimate knowledge of `ember-concurrency`'s internals would be possible. Something like:

```javascript
@task
@waitForGenerator
*doSomething() {
}
```

I don't have much experience authoring decorators, but wouldn't it be possible to implement a `waitForGenerator` decorator that does what I propose above -- wrap a `yield*` in begin/end async, so it would be the equivalent of `waitForPromise()` but for a generator function? Then it would be completely opaque to `ember-concurrency`.

If we go this route, I think I'd argue for putting it in `ember-test-waiters` rather than some other library since it's so similar to `waitForPromise`. What do you think?

**Comment by rwjblue** [comment]
Ya, I'm definitely game to try to figure out a pattern for that. It's not 100% obvious to me if the _default_ behavior should be to add the test helper (and therefore opt-in) or not (and therefore you'd opt-out).

**Comment by bendemboski** [comment]
Making it opt-out would involve modifying `ember-concurrency-decorators`, right? I suppose that's an option.

FWIW, [here](https://github.com/bendemboski/ember-test-waiters/commit/67e426b49dea1436c71fb1c9a9810372ce509732)'s my proof of concept of the idea. As written, it's not tied to `ember-concurrency` in any way, but of course it is tied to `ember-test-waiters`, and I'm not sure what other coroutine library people would be using along with Ember.

It may not belong in `ember-test-waiters` -- could easily be its own addon, or go in `ember-concurrency-decorators`, or could toss the whole idea and implement it in `ember-concurrency-decorators` as an argument to `@task`.

Anyway, curious to hear your thoughts.

**Comment by rwjblue** [comment]
Seems good generally speaking, but I think the spike would need a bit more work:

* support usage as a decorator and non-decorator (I would think non-decorator cases would just take the coroutine and return our wrapper coroutine function)
* consider supporting decorator usage of the other APIs (e.g. `@waitForPromise` would wrap a method that returns a promise and automatically wait for it)
* we should consider adding support to strip these decorators from builds without tests (as opposed to making the noop's) via a babel transform

**Comment by bendemboski** [comment]
> support usage as a decorator and non-decorator (I would think non-decorator cases would just take the coroutine and return our wrapper coroutine function)

yup, for sure

> consider supporting decorator usage of the other APIs (e.g. @waitForPromise would wrap a method that returns a promise and automatically wait for it)

I'm not sure I follow...doesn't it already do that? Once it has a non-decorator form, you could wrap any generator, and it would wait for any iterator returned from the function to iterate to completion. I can't imagine why you'd want that outside of a coroutine pattern, and I think this will work for all coroutine patterns, so what APIs are there to cover?

> we should consider adding support to strip these decorators from builds without tests (as opposed to making the noop's) via a babel transform

Sure, makes sense, but definitely outside my area of experience. Got any similar examples to point me to to get started?

**Comment by bendemboski** [comment]
Also, I wasn't sure this would end up in `ember-test-waiters`, although I'd like it to. But I was nervous about adding decorators because of compatibility issues with apps that don't have modern enough Ember or `ember-cli-babel` or whatever (my knowledge here is fuzzy). Is there a compatibility story that we can make happen here?

**Comment by rwjblue** [comment]
> Sure, makes sense, but definitely outside my area of experience. Got any similar examples to point me to to get started?

https://github.com/chadhietala/babel-plugin-strip-glimmer-utils does a similar thing (though not with decorators). 

> I was nervous about adding decorators because of compatibility issues with apps that don't have modern enough Ember or ember-cli-babel or whatever (my knowledge here is fuzzy). Is there a compatibility story that we can make happen here?

We can detect the `this.parent` to see what version of ember-cli-babel is present, as long as they are on ember-cli-babel@7.7.3 or higher we should be fine. When we detect an older version, our decorator support code can either be stripped completely or left inert (because the code in our addon will be "safe" but the consuming addon/app may not care).

**Comment by bendemboski** [comment]
Addressed in https://github.com/emberjs/ember-test-waiters/pull/173

**Comment by rwjblue** [comment]
👏 thank you @bendemboski!
