### ISSUE TITLE
'ember-concurrency/-task-property' was moved in e-c v2

### ISSUE THREAD

**Issue by pichfl** [bendemboski/ember-concurrency-test-waiter#29]
> an Ember addon is importing a private `ember-concurrency` module `'ember-concurrency/-task-property'` that has moved

https://github.com/bendemboski/ember-concurrency-test-waiter/blob/6243092359bd4dc75bfab3a52fe9469d1eadd26b/addon/define-modifier.js#L2

This has changed in ember-concurrency v2. I'm not entirely sure what the best way going forward would be, as I've seen #12 around the corner.

**Comment by bendemboski** [comment]
Hi @pichfl this is a good reminder -- since [this PR](https://github.com/emberjs/ember-test-waiters/pull/173) landed in `@ember/test-waiters` enabling the use of `@waitFor`/`waitFor()` on `ember-concurrency` task functions, this library is ready for deprecation. I'd recommend you switch your usages of it over to `waitFor` and bid `ember-concurrency-test-waiter` a fond farewell :)

**Comment by pichfl** [comment]
For anyone findig this issue and is looking to solve this quickly, this is how it works in a nutshell:

```js
import { task } from 'ember-concurrency';
import { waitFor } from 'ember-test-waiters';

//...

export default myClass {
  @task
  @waitFor
  *myTask() {}
}
```
