### ISSUE TITLE
Use the public APIs exposed in e-c PR

### ISSUE THREAD

**Issue by machty** [bendemboski/ember-concurrency-test-waiter#9]
This [ember-concurrency PR](https://github.com/machty/ember-concurrency/pull/302) moved around some internals (preserving the old names w a deprecation warning in cases where I know addons such as this made use of private/intimate API).

When you have a sec, could you run against this PR and fix any imports to private APIs and let me know if I missed anything?

**Comment by bendemboski** [comment]
@machty I think the only private API I use is `TaskProperty`, which your PR makes public via `import { TaskProperty } from 'ember-concurrency';`. I made that import change and ran against the PR and everything looks good.

What's the migration path here? Are you going to remove the old APIs/modules and major version bump `ember-concurrency`? If so, I'll probably just switch import paths and major version bump this addon, rather than muck with dynamic import paths...

**Comment by bendemboski** [comment]
Closing as this addon is now deprecated
